version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: msante-mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: psychapp
      MYSQL_USER: msante
      MYSQL_PASSWORD: msante123
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./db/schema.sql:/docker-entrypoint-initdb.d/01-schema.sql
      - ./db/seed-data.sql:/docker-entrypoint-initdb.d/02-seed-data.sql
    command: --default-authentication-plugin=mysql_native_password

  phpmyadmin:
    image: phpmyadmin:latest
    container_name: msante-phpmyadmin
    environment:
      PMA_HOST: mysql
      PMA_PORT: 3306
      PMA_USER: root
      PMA_PASSWORD: root
    ports:
      - "8081:80"
    depends_on:
      - mysql

volumes:
  mysql_data: